apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "serivan-app.fullname" . }}-conf
  labels:
    {{- include "serivan-app.labels" . | nindent 4 }}
data:
  DbName: "postgres"
  DbPort: {{ .Values.ConfigMapValues.DbPort | quote }}
  DbHost: {{ .Values.ConfigMapValues.DbHost }}
  ListenHost: {{ .Values.ConfigMapValues.ListenHost }}
  ListenPort: {{ .Values.ConfigMapValues.ListenPort | quote }}
