apiVersion: v1
kind: Secret
metadata:
  name: {{ include "serivan-app.fullname" . }}-secret
  labels:
    {{- include "serivan-app.labels" . | nindent 4 }}
data:
  # You can include additional key value pairs as you do with Opaque Secrets
  dbuser: {{ .Values.AppSecrets.dbuser | b64enc | quote }}
  dbpassword: {{ .Values.AppSecrets.dbpassword | b64enc | quote }}
